### ISSUE TITLE
Crashing immediately because of the nil value.

### ISSUE THREAD

**Issue by ytur** [googleads/googleads-consent-sdk-ios#1]
After consent form constructed and trying to load, crashing immediately at line 188 of PACView.m because of nil value of the bundleURL.

/// Loads the consent form HTML into the web view.
- (void)loadWebView {
  NSURL ***bundleURL** =
      [[NSBundle mainBundle] URLForResource:@"PersonalizedAdConsent" withExtension:@"bundle"];
  NSBundle *bundle = [NSBundle bundleWithURL:**bundleURL**];
  NSURL *URL = [bundle URLForResource:@"consentform" withExtension:@"html"];
  NSURLRequest *URLRequest = [[NSURLRequest alloc] initWithURL:URL];
  [_webView loadRequest:URLRequest];
}

**Comment by CrossProd** [comment]
You probably need to include "PersonalizedAdConsent.bundle" in your project and target.

**Comment by ytur** [comment]
![screen shot 2018-05-22 at 13 10 57](https://user-images.githubusercontent.com/2853842/40356517-f258e0c0-5dc1-11e8-8dcd-ae0bbb80cbf8.jpg)

it's already in there. Isn't that correct?

**Comment by hacknicity** [comment]
The pictures in the docs aren't loading for me, but step 3 in the "Manual Download" section explicitly states that the `PersonalizedAdConsent.bundle` file should be added to *your* target as a folder reference (so Xcode refers to the original file, and doesn't make its own copy): https://developers.google.com/admob/ios/eu-consent

**Comment by ytur** [comment]
**"PersonalizedAdConsent.bundle file should be added to your target as a folder reference "**

Thanks hacknicity. Your explanation make it clear the problem for me that I've mentioned.
