### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by ilyon** [googleads/googleads-consent-sdk-ios#18]
I follow these instructions to include it in my project.https://developers.google.com/admob/ios/eu-consent
But when using the Consent SDK, call requestConsentInfoUpdateForPublisherIdentifiers:completionHandler: on an instance of PACConsentInformation. I will get an error as below.
![image](https://user-images.githubusercontent.com/2276323/40697445-c6d816f0-63fc-11e8-9231-fecfa7b677bb.png)

**Comment by codenia** [comment]
I have the same error and no solution.

**Comment by rampara** [comment]
@ilyon if you our manually including the Consent SDK into you project, ensure you follow the instructions in our [developer docs](https://developers.google.com/admob/ios/eu-consent#manual_download).
