### ISSUE TITLE
What to do first: configureAds or requestConsent from user?

### ISSUE THREAD

**Issue by hitnova** [googleads/googleads-consent-sdk-ios#30]
Hello colleagues,

what do you think, is it Ok to initialise Google Ads before requesting the ads consent from the user?
Or by calling the `[GADMobileAds configureWithApplicationID:@"AppId"]` will be already some user personalised information collected and send to Google?

Thanks!

**Comment by ericleich** [comment]
You should get consent prior to calling `configureWithApplicationId:`.
