### ISSUE TITLE
Universal binary missing

### ISSUE THREAD

**Issue by hansemannn** [googleads/googleads-consent-sdk-ios#4]
The universal build of this project is missing so far. I have compiled it here for the devs requiring it:

[PersonalizedAdConsent.framework.zip](https://github.com/googleads/googleads-consent-sdk-ios/files/2026159/PersonalizedAdConsent.framework.zip)

Is there interest in having a deployment target to generate this? It's ready locally.

**Comment by rampara** [comment]
Closing this issue as those that require a universal binary can do so from source.
