### ISSUE TITLE
Usage of deprecated UIWebView

### ISSUE THREAD

**Issue by hansemannn** [googleads/googleads-consent-sdk-ios#6]
Unless this project is supposed to support iOS 7, it should use the iOS 8+ `WKWebView` class.

**Comment by ericleich** [comment]
The deployment target is indeed [7.0](https://github.com/googleads/googleads-consent-sdk-ios/blob/master/PersonalizedAdConsent/PersonalizedAdConsent.xcodeproj/project.pbxproj#L345). The Google Mobile Ads SDK still serves ads on iOS 7, so the Consent SDK needs to also support it.

**Comment by duytq94** [comment]
@ericleich did you have a plan to update it since Apple said:
The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.
